### PR TITLE
Setup remix to call strapi api with auth header

### PR DESCRIPTION
**Pull request by kiliman**
When calling the strapi API (either locally or in the cloud), you need to provide an API token via `Authorization: Bearer <token>` header.

This PR updates the fetch calls to include the correct headers.

Copy `.env.example` to `.env` and paste in the API key generated from your admin console.

>NOTE: You must also be running Strapi locally on `http://localhost:1337` or in the cloud. If in cloud, make sure you add `STRAPI_URL` to your `.env` file.

### CODE REVIEW

**Comment by kiliman** [comment]
I went through the strapi get started guide and created the content type for contacts
image

I created the API key
image

Pasted it into .env file
image

I was able to access and create contacts
image

**Comment by teodorazhelyazkova** [comment]
@kiliman Hi Michael, thank you for the PR. I just pulled it and added the API key that I generated locally in my Strapi admin but I still get this error in the console. You don't have the error at all on your side?
error

P.S. Also, I get these errors in the browser console which I think are not related to the error above but I just wanted to show them if it helps in some way.

Capture

**Comment by kiliman** [comment]
Is your strapi server running. It needs to be running at http://localhost:1337 

I did get that error the first time I tried your project. It was because it tried to connect to strapi and it wasn't running.

**Comment by teodorazhelyazkova** [comment]
> Is your strapi server running. It needs to be running at http://localhost:1337
> 
> I did get that error the first time I tried your project. It was because it tried to connect to strapi and it wasn't running.

Yes, the Strapi server is running, I am able to fetch the contacts from Strapi. On every interaction with the page (i.e. changing to different contact page) the error is popping up in the console. 
Capture

**Comment by kiliman** [comment]
Hmm. That is strange. I see you're on Windows. I wonder if that's the difference. I'll have to try it on my Windows VM.

**Comment by teodorazhelyazkova** [comment]
> Hmm. That is strange. I see you're on Windows. I wonder if that's the difference. I'll have to try it on my Windows VM.

It may be as the tutorial I followed was done on Mac as well. I am not sure if this mistake can be connected to some of the other issues I faced with this Remix app, as even though I followed the tutorial, I couldn't get the same behaviour. The main issues I have are 1. [Form input value in contacts/create not saved](https://github.com/PaulBratslavsky/freecodecamp-remix-strapi-final/issues/3) and 2. [Reloading page when adding a contact to favourites](https://github.com/PaulBratslavsky/freecodecamp-remix-strapi-final/issues/4) which is not the expected behaviour

**Comment by kiliman** [comment]
Hey, sorry I haven't been able to help out more. I got busy with work.

Are you still having issues? If so, let me know. I should have some time tomorrow to take a look.

**Comment by teodorazhelyazkova** [comment]
> Hey, sorry I haven't been able to help out more. I got busy with work.
> 
> Are you still having issues? If so, let me know. I should have some time tomorrow to take a look.

Hi @kiliman, yes I have the same issue, I haven't found a solution yet. However, I merged the branch though as I didn't have the API key in the app. Thanks a lot again for your time!

**Comment by kiliman** [comment]
I made a new PR #2. This should fix the error messages you were getting.

**Comment by PaulBratslavsky** [comment]
@kiliman I just want to first say you are awesome and thank you for your help.  

I am actually curios now, when I made the tutorial I may have used the old way of starting the project, since it was while back, and not use vite.  I should look into this and update accordingly.

**Comment by PaulBratslavsky** [comment]
@teodorazhelyazkova the two items the awesome @kiliman recommended should fix the issue.  I tested his fixes in your project and they worked.

1. Update the api key that you generate within Strapi Admin panel
2. And update the css import and your second error should go away as well

Let me know if have any issues or if you are getting any other errors.

**Comment by kiliman** [comment]
Yes, there have been some changes with Vite. It's definite that the URL imports are different.

https://remix.run/docs/en/main/guides/vite#fix-up-css-imports-referenced-in-links

Thanks for the kind words. I'm glad I was able to help.

**Comment by PaulBratslavsky** [comment]
@teodorazhelyazkova I think I know the issue you are running into.

I did not set the header in my video tutorial. Here is the code from my getContacts function in the data.server.ts.` file.  

```
export async function getContacts(q: string | null) {
  
  const query = qs.stringify({
    filters: {
      $or: [
        { first: { $contains: q }},
        { last: { $contains: q }},
        { twitter: { $contains: q }},
      ]
    },
    pagination: {
      pageSize: 50,
      page: 1,
    },
  })
  
  try {
    const response = await fetch( url + "/api/contacts?" + query);
    const data = await response.json();
    const flattenAttributesData = flattenAttributes(data.data);
    return flattenAttributesData;
  } catch (error) {
    console.log(error);
    // throw new Error("Oh no! Something went wrong!");
    throw new Response("Oh no! Something went wrong!", {
      status: 500,
      statusText: "This is my custom error!"
    });
  }
}
```

Then, in my Strapi application, I set public permissions as follows. Because it is public, I don't need to create an API token.



In your project, you are seating the header, which requires a bearer token.
Your getContacts function is found in the `data.server.ts.` file.  

```
function strapiHeaders() {
    return {
        Authorization: `Bearer ${process.env.STRAPI_TOKEN!}`,
    };
}

export async function getContacts(q?: string | null) {
    const query = qs.stringify({
        filters: {
            $or: [
                { first: { $contains: q } },
                { last: { $contains: q } },
                { twitter: { $contains: q } },
            ],
        },
        pagination: {
            pageSize: 50,
            page: 1,
        },
    });

    try {
        const response = await fetch(STRAPI_URL + '/api/contacts?' + query, {
            headers: strapiHeaders(),
        });
    
        const data = await response.json();
        const flattenContactsAttributesData = flattenContactsAttributes(
            data.data,
        );

        return flattenContactsAttributesData;
    } catch (error) {
        console.log(error);
        throw new Error('Oh no! Something went wrong');
    }
}

```

That is why you need to create an API token in Strapi admin and see the permissions you want as an additional step.  

In Michael's example, he set it as "full access," but you can specify just the endpoint you want and what access you want.

Just like in this example.



I hope this clears things up.

**Comment by kiliman** [comment]
Ah. I hadn't looked at your tutorial and had zero experience with Strapi. I just followed the getting started guide to get it up and running. I hadn't read enough to know there was a public option.

Anyway, at least she knows how to handle API tokens if the need arises.

**Comment by teodorazhelyazkova** [comment]
@kiliman @PaulBratslavsky you are both awesome, thank you! 

The error was fixed with Michael's [2nd PR](https://github.com/teodorazhelyazkova/remix-contacts-app/pull/2) and this solution also fixed the other two issues I logged in [Paul's repo](https://github.com/PaulBratslavsky/freecodecamp-remix-strapi-final) 1. [Form input value in contacts/create not saved](https://github.com/PaulBratslavsky/freecodecamp-remix-strapi-final/issues/3) and 2. [Reloading page when adding a contact to favourites](https://github.com/PaulBratslavsky/freecodecamp-remix-strapi-final/issues/4) so I will add comments and close those as well.

Paul, thanks for the clarification on the API token. I have set up the token according to Michael's suggestion, however, it's not needed in this case as I made the contacts endpoints public when I followed your tutorial.

**Comment by PaulBratslavsky** [comment]
@kiliman glad that the Strapi docs were helpful.  Your answer was spot on. Thanks for your help again.

**Pull request merged**
